# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konjure < Formula
  desc "Manifest appear!"
  homepage "https://github.com/thestormforge/konjure/"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thestormforge/konjure/releases/download/v0.4.2/konjure-darwin-amd64.tar.gz"
      sha256 "457c52a374bf125d318563c287d7d3742587ec575fe6a5b79ae5a3dad91ab47a"

      def install
        bin.install "konjure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thestormforge/konjure/releases/download/v0.4.2/konjure-darwin-arm64.tar.gz"
      sha256 "b4a51e122dd1b28c319117c9ca87bc9acababbadfb220877e021ddf0733a2676"

      def install
        bin.install "konjure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thestormforge/konjure/releases/download/v0.4.2/konjure-linux-amd64.tar.gz"
      sha256 "74d2000747add28c1d9e9097deee59cfbc10cb1b0dfb61bc5a7a9359b0a03882"

      def install
        bin.install "konjure"
      end
    end
  end
end
