# This file was generated by GoReleaser. DO NOT EDIT.
class Redskyctl < Formula
  desc "Release with Confidence"
  homepage "https://www.stormforge.io/"
  version "1.8.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thestormforge/optimize-controller/releases/download/v1.8.1/redskyctl-darwin-amd64.tar.gz"
    sha256 "262a1fc923b0dfb081ea3f5b3589f6c43397d06bb6f6076351ab10501691db66"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/thestormforge/optimize-controller/releases/download/v1.8.1/redskyctl-linux-amd64.tar.gz"
    sha256 "d174f79a7f7bfccb4c2b78139fabed92bc671ba71f10f5b16021d07db207da81"
  end

  def install
    bin.install "redskyctl"
  end
end
