# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redskyctl < Formula
  desc "Release with Confidence"
  homepage "https://www.stormforge.io/"
  version "1.10.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thestormforge/optimize-controller/releases/download/v1.10.0/redskyctl-darwin-amd64.tar.gz"
    sha256 "415caeb9430098df3f528f7800e084cc1a68cce53e61312604072eab9f23b0de"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/thestormforge/optimize-controller/releases/download/v1.10.0/redskyctl-linux-amd64.tar.gz"
    sha256 "dd2f4cd815fd3f38b2858820ff08de709454e824c8452d85761c3d4ebd6ad04c"
  end

  def install
    bin.install "redskyctl"
  end
end
