# This file was generated by GoReleaser. DO NOT EDIT.
class Redskyctl < Formula
  desc "Release with Confidence"
  homepage "https://www.stormforge.io/"
  version "1.9.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thestormforge/optimize-controller/releases/download/v1.9.0/redskyctl-darwin-amd64.tar.gz"
    sha256 "1c77831a4af220e30d0dfeb3a757137f4e77b8dbeeeaffb72b4ca90085252a7a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/thestormforge/optimize-controller/releases/download/v1.9.0/redskyctl-linux-amd64.tar.gz"
    sha256 "ff507a24e6036aa2098ffa0e24a17479dc1c911d515f7bcb77138f1175337264"
  end

  def install
    bin.install "redskyctl"
  end
end
