# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stormforge < Formula
  desc "Release with Confidence"
  homepage "https://www.stormforge.io/"
  version "2.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thestormforge/optimize-controller/releases/download/v2.0.1/stormforge-darwin-arm64.tar.gz"
      sha256 "8f518b67442ba9db2c799c85c4fe6fea9f7ca1883b46db0174c029f5a06a1ffc"
    end
    if Hardware::CPU.intel?
      url "https://github.com/thestormforge/optimize-controller/releases/download/v2.0.1/stormforge-darwin-amd64.tar.gz"
      sha256 "737f264d887c894648e78beb8e0dddc6986fee4ddbb3815c47c8c90cc05c4e60"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thestormforge/optimize-controller/releases/download/v2.0.1/stormforge-linux-amd64.tar.gz"
      sha256 "f0a419bb4f4111c3d7b04e85b03b3cbeaa0acf608208d27cd53004fd542a4581"
    end
  end

  def install
    bin.install "stormforge"
  end
end
