# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StormforgeBeta < Formula
  desc "Release with Confidence"
  homepage "https://www.stormforge.io/"
  version "3.0.0-beta.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_darwin_arm64.tar.gz"
      sha256 "6644fa5fc0ab35a0ef12a788131aa96fb6ba869fd2ae03ec90dcdc6dc98e154b"

      def install
        bin.install "stormforge"
      end
    end
    if Hardware::CPU.intel?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_darwin_amd64.tar.gz"
      sha256 "3d1c2d3c8f23764bba4b15b5fdf260864ad3ec809061e59283e76329e0247bd9"

      def install
        bin.install "stormforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_linux_arm64.tar.gz"
      sha256 "574430d272dfe34c5c7b3d41d14ac9e5ff89344fc859c3c84a09806e0c2883d8"

      def install
        bin.install "stormforge"
      end
    end
    if Hardware::CPU.intel?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_linux_amd64.tar.gz"
      sha256 "7360558b62a895756ec3063fb2f327eeb56bca37fb8859d87ab72a6b13d73374"

      def install
        bin.install "stormforge"
      end
    end
  end

  def caveats
    <<~EOS
      This is a pre-release version.
    EOS
  end
end
