# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StormforgeCli < Formula
  desc "Release with Confidence"
  homepage "https://www.stormforge.io/"
  version "3.0.0-beta.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.1/stormforge_3.0.0-beta.1_darwin_arm64.tar.gz"
      sha256 "4ecc7829e760f76be57f501b094bca9689416c12ba2d58788b57ee19e0c2778d"

      def install
        bin.install "stormforge"
      end
    end
    if Hardware::CPU.intel?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.1/stormforge_3.0.0-beta.1_darwin_amd64.tar.gz"
      sha256 "c062fa18ad6f3671f201f2c3b159fa3c889c8b3c93248cee0ef486b9f45aa414"

      def install
        bin.install "stormforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.1/stormforge_3.0.0-beta.1_linux_arm64.tar.gz"
      sha256 "a651483701ec8a969eb5e3d440f94b87e5ccbe42e58d5fcb82fcdf5255194bef"

      def install
        bin.install "stormforge"
      end
    end
    if Hardware::CPU.intel?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.1/stormforge_3.0.0-beta.1_linux_amd64.tar.gz"
      sha256 "2f1b1ecf43ae07151762ec73bfbeed760ea64efada247568a739589049cd1c16"

      def install
        bin.install "stormforge"
      end
    end
  end
end
