# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StormforgeBeta < Formula
  desc "Release with Confidence"
  homepage "https://www.stormforge.io/"
  version "3.0.0-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_darwin_amd64.tar.gz"
      sha256 "5c73e606919c1c1eba5405fc0132eeb2f0297a042f42625e190f1e79a8dc63d2"

      def install
        bin.install "stormforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_darwin_arm64.tar.gz"
      sha256 "d2b7bb1531c230d128d7430fc99895fd05b117ce8cc0a0bc118887e18341ea12"

      def install
        bin.install "stormforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_linux_amd64.tar.gz"
      sha256 "b3764b56973d614a9a1ad1366f274cfbce501130c649ba9aa93eff1a5307aa50"

      def install
        bin.install "stormforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.stormforge.io/stormforge-cli/v3.0.0-beta.2/stormforge_3.0.0-beta.2_linux_arm64.tar.gz"
      sha256 "7186429b4ac2d89a1f69fc0685a7afaa8466ce2f0bfeacf16936c107833c7f7c"

      def install
        bin.install "stormforge"
      end
    end
  end

  def caveats
    <<~EOS
      This is a pre-release version.
    EOS
  end
end
